apiVersion: apps/v1
kind: Deployment
metadata:
  name: hookify
spec:
  selector:
    matchLabels:
      app: hookify
  replicas: 1
  template:
    metadata:
      labels:
        app: hookify
        version: v1
    spec:
      containers:
        - name: hookify
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      serviceAccountName: hookify-pipeline-runner
      serviceAccount: hookify-pipeline-runner
#test
---
apiVersion: v1
kind: Service
metadata:
  name: hookify-service
spec:
  selector:
    app: hookify
  ports:
    - port: 8000
      name: http
